# Generated by Django 5.2.4 on 2025-08-10 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_quiz_options_alter_option_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="api.institution",
            ),
        ),
    ]
