# Generated by Django 5.2.4 on 2025-08-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_program_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="institution_description",
            field=models.TextField(null=True),
        ),
    ]
