# Generated by Django 5.2.4 on 2025-08-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_institution_institution_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="institution_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
