# Generated by Django 5.2.4 on 2025-08-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_institution_institution_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="course_institution",
        ),
    ]
