# Generated by Django 5.2.4 on 2025-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_career"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="career",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
