# Generated by Django 5.2.4 on 2025-08-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_career_career"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="institution_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
