# Generated by Django 5.2.4 on 2025-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_institution_institution_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="institution_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="institution_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
