# Generated by Django 5.2.4 on 2025-08-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_program_institution_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="institution_body",
        ),
        migrations.RemoveField(
            model_name="program",
            name="institution_description",
        ),
    ]
