# Generated by Django 5.2.4 on 2025-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_program_institution_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
