# Generated by Django 5.2.4 on 2025-08-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_institution_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="institution_logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
    ]
