# Generated by Django 5.2.4 on 2025-08-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_institution_institution_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="institution_website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
